# Generated by Django 5.2 on 2025-04-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamescore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
